=== FrontedDevelopers/Proyecto2/AE2-XML,DTD,Y_XSD_Final/bibliotecaXsdRestriction.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="LIBROS">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Libro">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tipo_clase">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="novela"></xs:enumeration>
                            <xs:enumeration value="infantil"></xs:enumeration>
                            <xs:enumeration value="didactico"></xs:enumeration>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                    <xs:element name="Titulo_libro" type="xs:string" />
                    <xs:element name="indice_libro">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="capitulo">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="contenido_cap">
                                  <xs:complexType>
                                    <xs:attribute name="enlace_libro" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="titulo_capitulo" type="xs:string" />
                              </xs:sequence>
                              <xs:attribute name="num_capitulo" type="xs:unsignedByte" use="required" />
                              <xs:attribute name="num_paginas_cap" type="xs:unsignedByte" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="sipnosis" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required" />
                  <xs:attribute name="num_paginas_libro" type="xs:unsignedByte" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="REVISTAS">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Revista">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tipo_clase_revista">
                      <xs:simpleType>
                          <xs:restriction base="xs:string">
                              <xs:enumeration value="informatica"></xs:enumeration>
                              <xs:enumeration value="corazon"></xs:enumeration>
                              <xs:enumeration value="coches"></xs:enumeration>
                              <xs:enumeration value="investigacion"></xs:enumeration>
                              <xs:enumeration value="otros"></xs:enumeration>
                          </xs:restriction>
                      </xs:simpleType>
                  </xs:element>
                    <xs:element name="Titulo_revista" type="xs:string" />
                    <xs:element name="numero_revista" type="xs:unsignedByte" />
                    <xs:element name="indice_revista">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="seccion_revista">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Titulo_seccion" type="xs:string" />
                                <xs:element name="contenido_revista">
                                  <xs:complexType>
                                    <xs:attribute name="enlace" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="num_seccion" type="xs:unsignedByte" use="required" />
                              <xs:attribute name="num_paginas_rev" type="xs:unsignedByte" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required" />
                  <xs:attribute name="num_paginas_revista" type="xs:unsignedShort" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="PERIODICOS">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="periodico">
                <xs:complexType>
                  <xs:sequence>
                     <xs:element name="tipo_clase">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="nacional"></xs:enumeration>
                                <xs:enumeration value="internacional"></xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="indice_periodico">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="seccion_periodico">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="articulo">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="titulo_periodico" type="xs:string" />
                                      <xs:element name="contenido_periodico">
                                        <xs:complexType>
                                          <xs:attribute name="enlace_periodico" type="xs:string" use="required" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="autor" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="tipo_seccion" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required" />
                 <xs:attribute name="fecha_publicacion" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== FrontedDevelopers/Proyecto2/AE2-XML,DTD,Y_XSD_Final/bibliotecaXsdRestriction.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation= "bibliotecaXsdRestriction.xsd">
    <LIBROS>

        <Libro id="L0001"  num_paginas_libro="200">
            <tipo_clase>novela</tipo_clase>
            <Titulo_libro>El Señor de los anillos: La Comunidad del Anillo</Titulo_libro>
            <indice_libro>
                <capitulo num_capitulo="1" num_paginas_cap="100">
                    <contenido_cap enlace_libro="http://web.seducoahuila.gob.mx/biblioweb/upload/J.R.R.%20Tolkien%20La%20Comunidad%20del%20anillo%20I.pdf"></contenido_cap>
                    <titulo_capitulo>"De los hobbits"</titulo_capitulo>
                </capitulo>
                <capitulo num_capitulo="2" num_paginas_cap="80">
                    <contenido_cap enlace_libro="http://web.seducoahuila.gob.mx/biblioweb/upload/J.R.R.%20Tolkien%20La%20Comunidad%20del%20anillo%20I.pdf"></contenido_cap>
                    <titulo_capitulo>"De la hierba para pipa"</titulo_capitulo>
                </capitulo>
                <capitulo num_capitulo="3" num_paginas_cap="20">
                    <contenido_cap enlace_libro="http://web.seducoahuila.gob.mx/biblioweb/upload/J.R.R.%20Tolkien%20La%20Comunidad%20del%20anillo%20I.pdf "></contenido_cap>
                    <titulo_capitulo>"De la ordenación de la Comarca"</titulo_capitulo>
                </capitulo>
            </indice_libro>
            <sipnosis>Resumen del libro: narra el viaje del protagonista principal, Frodo Bolsón, 
            hobbit de la Comarca, para destruir el Anillo Único y la consiguiente guerra que provocará el enemigo para recuperarlo, 
            ya que es la principal fuente de poder de su creador, el Señor oscuro, Sauron.
            </sipnosis>


        </Libro>

        <Libro id="L0002"  num_paginas_libro="70">
            
            <tipo_clase>infantil</tipo_clase>
            <Titulo_libro>El Patito Feo</Titulo_libro>
            <indice_libro>
                <capitulo num_capitulo="1" num_paginas_cap="15">
                    <contenido_cap enlace_libro="http://bibliotecadigital.ilce.edu.mx/Colecciones/ObrasClasicas/_docs/ElPrincipito.pdf"></contenido_cap>
                    <titulo_capitulo>"Capitulo I"</titulo_capitulo>
                </capitulo>
                <capitulo num_capitulo="2" num_paginas_cap="35">
                    <contenido_cap enlace_libro="http://bibliotecadigital.ilce.edu.mx/Colecciones/ObrasClasicas/_docs/ElPrincipito.pdf"></contenido_cap>
                    <titulo_capitulo>"Capitulo II"</titulo_capitulo>
                </capitulo>
                <capitulo num_capitulo="3" num_paginas_cap="20">
                    <contenido_cap enlace_libro="http://bibliotecadigital.ilce.edu.mx/Colecciones/ObrasClasicas/_docs/ElPrincipito.pdf"></contenido_cap>
                    <titulo_capitulo>"Capitulo III"</titulo_capitulo>
                </capitulo>
            </indice_libro>

            <sipnosis>Resumen del libro: trata de la historia de un pequeño príncipe que parte de su asteroide a una travesía por el universo, en la cual descubre 
            la extraña forma en que los adultos ven la vida y comprende el valor del amor y la amistad.
            </sipnosis>   

        </Libro>

        <Libro id="L0003"  num_paginas_libro="70">
            <tipo_clase>didactico</tipo_clase>
            <Titulo_libro>Aprende a programar en Edix</Titulo_libro>
            <indice_libro>
                <capitulo num_capitulo="1" num_paginas_cap="15">
                    <contenido_cap enlace_libro="https://www.edix.com/es/"></contenido_cap>
                    <titulo_capitulo>"Aprende HTML"</titulo_capitulo>
                </capitulo>
                <capitulo num_capitulo="2" num_paginas_cap="35">
                    <contenido_cap enlace_libro="https://www.edix.com/es/"></contenido_cap>
                    <titulo_capitulo>"Aprende CSS"</titulo_capitulo>
                </capitulo>
                <capitulo num_capitulo="3" num_paginas_cap="20">
                    <contenido_cap enlace_libro="https://www.edix.com/es/"></contenido_cap>
                    <titulo_capitulo>"Aprende XSD"</titulo_capitulo>
                </capitulo>
            </indice_libro>

            <sipnosis>Somos la escuela que crea a los profesionales digitales que necesitan las empresas. Estamos aquí para hacer tu Revolución Profesional. Formamos a Digital Workers. Lo hacemos a 
            través de nuestra escuela de profesiones digitales y de Formación Profesional (FP) a distancia.
            </sipnosis> 
        </Libro>

    </LIBROS>

    <REVISTAS>

        <Revista id="R0001"  num_paginas_revista="300">
            <tipo_clase_revista>informatica</tipo_clase_revista>
            <Titulo_revista>Aprende a Programar de 0</Titulo_revista>
            <numero_revista>1</numero_revista>
            <indice_revista>
                <seccion_revista num_seccion="1" num_paginas_rev="100">
                    <Titulo_seccion>Aprende Java</Titulo_seccion>
                    <contenido_revista enlace="https://www.java.com/es/"></contenido_revista>
                </seccion_revista>
                 <seccion_revista num_seccion="2" num_paginas_rev="100">
                    <Titulo_seccion>Aprende Html</Titulo_seccion>
                    <contenido_revista enlace="https://developer.mozilla.org/es/docs/Web/HTML"></contenido_revista>
                </seccion_revista>
                 <seccion_revista num_seccion="3" num_paginas_rev="100">
                    <Titulo_seccion>Aprende Xml</Titulo_seccion>
                    <contenido_revista enlace="https://developer.mozilla.org/es/docs/Web/XML/XML_introduction"></contenido_revista>
                </seccion_revista>
            </indice_revista>

        </Revista>

        <Revista id="R0002"  num_paginas_revista="250">
            <tipo_clase_revista>corazon</tipo_clase_revista>
            <Titulo_revista>Hola !</Titulo_revista>
            <numero_revista>1</numero_revista>
            <indice_revista>
                <seccion_revista num_seccion="1" num_paginas_rev="50">
                    <Titulo_seccion>La vida de Isa Pantoja</Titulo_seccion>
                    <contenido_revista enlace="https://www.hola.com/"></contenido_revista>
                </seccion_revista>
                 <seccion_revista num_seccion="2" num_paginas_rev="100">
                    <Titulo_seccion>La vida de Nadal</Titulo_seccion>
                    <contenido_revista enlace="https://www.hola.com/"></contenido_revista>
                </seccion_revista>
                 <seccion_revista num_seccion="3" num_paginas_rev="100">
                    <Titulo_seccion>La vida de Felipe VI</Titulo_seccion>
                    <contenido_revista enlace="https://www.hola.com/"></contenido_revista>
                </seccion_revista>
            </indice_revista> 
            
        </Revista>

        <Revista id="R0003"  num_paginas_revista="200">
            <tipo_clase_revista>coches</tipo_clase_revista>
            <Titulo_revista>Revista Motor !</Titulo_revista>
            <numero_revista>1</numero_revista>
            <indice_revista>
                <seccion_revista num_seccion="1" num_paginas_rev="50">
                    <Titulo_seccion>Coches BMW</Titulo_seccion>
                    <contenido_revista enlace="https://www.motor.com.co/"></contenido_revista>
                </seccion_revista>
                 <seccion_revista num_seccion="2" num_paginas_rev="50">
                    <Titulo_seccion>Coches Audi</Titulo_seccion>
                    <contenido_revista enlace="https://www.motor.com.co/"></contenido_revista>
                </seccion_revista>
                 <seccion_revista num_seccion="3" num_paginas_rev="100">
                    <Titulo_seccion>Coches Mercedes</Titulo_seccion>
                    <contenido_revista enlace="https://www.motor.com.co/"></contenido_revista>
                </seccion_revista>
            </indice_revista> 

        </Revista>
        
        <Revista id="R0004"  num_paginas_revista="160">
            <tipo_clase_revista>investigacion</tipo_clase_revista>
            <Titulo_revista>National Geographic</Titulo_revista>
            <numero_revista>1</numero_revista>
            <indice_revista>
                <seccion_revista num_seccion="1" num_paginas_rev="50">
                    <Titulo_seccion>Todo sobre animales</Titulo_seccion>
                    <contenido_revista enlace="https://www.nationalgeographic.com.es/"></contenido_revista>
                </seccion_revista>
                 <seccion_revista num_seccion="2" num_paginas_rev="50">
                    <Titulo_seccion>Todo sobre el mar</Titulo_seccion>
                    <contenido_revista enlace="https://www.nationalgeographic.com.es/"></contenido_revista>
                </seccion_revista>
                 <seccion_revista num_seccion="3" num_paginas_rev="100">
                    <Titulo_seccion>Todo sobre el espacio</Titulo_seccion>
                    <contenido_revista enlace="https://www.nationalgeographic.com.es/"></contenido_revista>
                </seccion_revista>
            </indice_revista> 

        </Revista> 

        <Revista id="R0005"  num_paginas_revista="160">
            <tipo_clase_revista>otros</tipo_clase_revista>
            <Titulo_revista>Cosmopolitan</Titulo_revista>
            <numero_revista>1</numero_revista>
            <indice_revista>
                <seccion_revista num_seccion="1" num_paginas_rev="50">
                    <Titulo_seccion>Moda</Titulo_seccion>
                    <contenido_revista enlace="https://www.cosmopolitan.com/es/"></contenido_revista>
                </seccion_revista>
